-- MySQL Script generated by MySQL Workbench
-- Tue Jun  4 17:32:31 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema DriverCourses
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `DriverCourses` ;

-- -----------------------------------------------------
-- Schema DriverCourses
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DriverCourses` DEFAULT CHARACTER SET utf8 ;
USE `DriverCourses` ;

-- -----------------------------------------------------
-- Table `DriverCourses`.`Students`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DriverCourses`.`Students` ;

CREATE TABLE IF NOT EXISTS `DriverCourses`.`Students` (
  `idStudents` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Category` VARCHAR(1) NOT NULL,
  PRIMARY KEY (`idStudents`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idStudents_UNIQUE` ON `DriverCourses`.`Students` (`idStudents` ASC);


-- -----------------------------------------------------
-- Table `DriverCourses`.`Course`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DriverCourses`.`Course` ;

CREATE TABLE IF NOT EXISTS `DriverCourses`.`Course` (
  `idCourse` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Cost` INT UNSIGNED NOT NULL,
  `DurationInDays` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idCourse`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idCourse_UNIQUE` ON `DriverCourses`.`Course` (`idCourse` ASC);


-- -----------------------------------------------------
-- Table `DriverCourses`.`Attendance`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DriverCourses`.`Attendance` ;

CREATE TABLE IF NOT EXISTS `DriverCourses`.`Attendance` (
  `idAttendance` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Date` DATETIME NOT NULL,
  `IsPresent` TINYINT(1) NOT NULL,
  `Students_idStudents` INT NOT NULL,
  `Course_idCourse` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idAttendance`, `Students_idStudents`, `Course_idCourse`),
  CONSTRAINT `fk_Attendance_Students1`
    FOREIGN KEY (`Students_idStudents`)
    REFERENCES `DriverCourses`.`Students` (`idStudents`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Attendance_Course1`
    FOREIGN KEY (`Course_idCourse`)
    REFERENCES `DriverCourses`.`Course` (`idCourse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idAttendance_UNIQUE` ON `DriverCourses`.`Attendance` (`idAttendance` ASC);

CREATE INDEX `fk_Attendance_Students1_idx` ON `DriverCourses`.`Attendance` (`Students_idStudents` ASC);

CREATE INDEX `fk_Attendance_Course1_idx` ON `DriverCourses`.`Attendance` (`Course_idCourse` ASC);


-- -----------------------------------------------------
-- Table `DriverCourses`.`DrivingPractice`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DriverCourses`.`DrivingPractice` ;

CREATE TABLE IF NOT EXISTS `DriverCourses`.`DrivingPractice` (
  `idDrivingPractice` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Students_idStudents` INT NOT NULL,
  `Date` DATETIME NOT NULL,
  `Instructor` VARCHAR(45) NOT NULL,
  `DurationInHours` FLOAT NOT NULL,
  PRIMARY KEY (`idDrivingPractice`, `Students_idStudents`),
  CONSTRAINT `fk_DrivingPractice_Students1`
    FOREIGN KEY (`Students_idStudents`)
    REFERENCES `DriverCourses`.`Students` (`idStudents`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idDrivingPractice_UNIQUE` ON `DriverCourses`.`DrivingPractice` (`idDrivingPractice` ASC);

CREATE INDEX `fk_DrivingPractice_Students1_idx` ON `DriverCourses`.`DrivingPractice` (`Students_idStudents` ASC);


-- -----------------------------------------------------
-- Table `DriverCourses`.`DrivingErrors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DriverCourses`.`DrivingErrors` ;

CREATE TABLE IF NOT EXISTS `DriverCourses`.`DrivingErrors` (
  `idDrivingErrors` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Students_idStudents` INT NOT NULL,
  `Date` DATETIME NOT NULL,
  `ErrorDescription` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`idDrivingErrors`, `Students_idStudents`),
  CONSTRAINT `fk_DrivingErrors_Students1`
    FOREIGN KEY (`Students_idStudents`)
    REFERENCES `DriverCourses`.`Students` (`idStudents`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idDrivingErrors_UNIQUE` ON `DriverCourses`.`DrivingErrors` (`idDrivingErrors` ASC);

CREATE INDEX `fk_DrivingErrors_Students1_idx` ON `DriverCourses`.`DrivingErrors` (`Students_idStudents` ASC);


-- -----------------------------------------------------
-- Table `DriverCourses`.`TestResults`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DriverCourses`.`TestResults` ;

CREATE TABLE IF NOT EXISTS `DriverCourses`.`TestResults` (
  `idTestResults` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Students_idStudents` INT NOT NULL,
  `Date` DATETIME NOT NULL,
  `Score` FLOAT NOT NULL,
  PRIMARY KEY (`idTestResults`, `Students_idStudents`),
  CONSTRAINT `fk_TestResults_Students1`
    FOREIGN KEY (`Students_idStudents`)
    REFERENCES `DriverCourses`.`Students` (`idStudents`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idTestResults_UNIQUE` ON `DriverCourses`.`TestResults` (`idTestResults` ASC);

CREATE INDEX `fk_TestResults_Students1_idx` ON `DriverCourses`.`TestResults` (`Students_idStudents` ASC);


-- -----------------------------------------------------
-- Table `DriverCourses`.`ExamResults`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DriverCourses`.`ExamResults` ;

CREATE TABLE IF NOT EXISTS `DriverCourses`.`ExamResults` (
  `idExamResults` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Students_idStudents` INT NOT NULL,
  `Date` DATETIME NOT NULL,
  `IsPresent` TINYINT NOT NULL,
  PRIMARY KEY (`idExamResults`, `Students_idStudents`),
  CONSTRAINT `fk_ExamResults_Students1`
    FOREIGN KEY (`Students_idStudents`)
    REFERENCES `DriverCourses`.`Students` (`idStudents`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idExamResults_UNIQUE` ON `DriverCourses`.`ExamResults` (`idExamResults` ASC);

CREATE INDEX `fk_ExamResults_Students1_idx` ON `DriverCourses`.`ExamResults` (`Students_idStudents` ASC);


-- -----------------------------------------------------
-- Table `DriverCourses`.`Course_has_Students`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `DriverCourses`.`Course_has_Students` ;

CREATE TABLE IF NOT EXISTS `DriverCourses`.`Course_has_Students` (
  `idCourse_has_Students` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Students_idStudents` INT NOT NULL,
  `Course_idCourse` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idCourse_has_Students`),
  CONSTRAINT `fk_Course_has_Students_Students1`
    FOREIGN KEY (`Students_idStudents`)
    REFERENCES `DriverCourses`.`Students` (`idStudents`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Course_has_Students_Course1`
    FOREIGN KEY (`Course_idCourse`)
    REFERENCES `DriverCourses`.`Course` (`idCourse`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `idCourse_has_Students_UNIQUE` ON `DriverCourses`.`Course_has_Students` (`idCourse_has_Students` ASC);

CREATE INDEX `fk_Course_has_Students_Students1_idx` ON `DriverCourses`.`Course_has_Students` (`Students_idStudents` ASC);

CREATE INDEX `fk_Course_has_Students_Course1_idx` ON `DriverCourses`.`Course_has_Students` (`Course_idCourse` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
